apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: decision-aggregator-scaler
  namespace: fraud-detection
spec:
  scaleTargetRef:
    name: decision-aggregator
  minReplicaCount: 1
  maxReplicaCount: 6
  cooldownPeriod:  30
  pollingInterval: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: fraud-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
        consumerGroup:    decision-aggregator-group
        topic:            fraud-decisions
        lagThreshold:     "10"
        offsetResetPolicy: latest