apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: feature-engineering-scaler
  namespace: fraud-detection
spec:
  scaleTargetRef:
    name: feature-engineering
  minReplicaCount: 1
  maxReplicaCount: 6
  cooldownPeriod:  30
  pollingInterval: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: fraud-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
        consumerGroup:    feature-engineering-group
        topic:            transactions-raw
        lagThreshold:     "10"
        offsetResetPolicy: latest