FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    kafka-python-ng==2.2.3 \
    psycopg2-binary==2.9.9

COPY src/ ./src/

ENV PYTHONPATH=/app:/app/src
ENV PYTHONUNBUFFERED=1

CMD ["python", "src/main.py"]