apiVersion: v1
kind: Secret
metadata:
  name: fraud-secrets
  namespace: fraud-detection
type: Opaque
stringData:
  kafka-bootstrap: "fraud-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  redis-host: "redis-master.fraud-detection.svc.cluster.local"
  postgres-url: "postgresql://postgres:localdev@postgres-postgresql.fraud-detection:5432/fraud_db"