image:
  repository: feature-engineering
  tag: latest
  pullPolicy: Never

kafka:
  bootstrapServers: "fraud-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topicRaw: "transactions-raw"
  topicFeatures: "transactions-scored"

redis:
  host: "redis-master.fraud-detection.svc.cluster.local"
  port: "6379"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"