image:
  repository: transaction-api
  tag: latest
  pullPolicy: Never

kafka:
  bootstrapServers: "fraud-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  topicRaw: "transactions-raw"

service:
  port: 8000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"